version: '3.1'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    volumes:
      - ./:/var/www/html
      - ./docker/logs/apache_log:/var/log/apache2
      - ./docker/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/ssl:/etc/apache2/ssl
    ports:
      - "80:80"
      - "443:443"
